# Generated by Django 5.2.6 on 2025-09-30 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resort', '0003_activity_alter_gallery_image_placeholder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('room_category', models.CharField(choices=[('availability', 'Based on Availability'), ('pond_view', 'Pond View'), ('garden_view', 'Garden View'), ('long_house', 'Long House')], max_length=20)),
                ('number_of_rooms', models.IntegerField()),
                ('room_types', models.JSONField(default=dict, help_text='Room type quantities as JSON')),
                ('meal_plan', models.CharField(choices=[('ep', 'EP'), ('bb', 'B&B'), ('map', 'MAP'), ('ap', 'AP'), ('1n2d_jp', '1N/2D JP'), ('2n3d_jp', '2N/3D JP'), ('3n4d_jp', '3N/4D JP')], max_length=20)),
                ('total_adults', models.IntegerField()),
                ('total_children', models.IntegerField(default=0)),
                ('booked_by', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('company', 'Company'), ('complementary', 'Complementary')], max_length=20)),
                ('payment_currency', models.CharField(choices=[('NRS', 'NRS'), ('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='backoffice.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('viewer', 'Viewer'), ('admin', 'Admin')], default='agent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
