# Generated by Django 5.2.6 on 2025-09-30 18:39

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_reservationauditlog_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationauditlog',
            name='changes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
