# Generated by Django 5.2.6 on 2025-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4 recommended)', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_thumbnail',
            field=models.CharField(blank=True, help_text='Thumbnail image URL for video', max_length=200),
        ),
        migrations.AddField(
            model_name='resort',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Hero background video (MP4 recommended, under 10MB)', null=True, upload_to='videos/'),
        ),
    ]
