# Generated by Django 5.2.6 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_gallery_media_type_gallery_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Activity name', max_length=100)),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=200)),
                ('full_description', models.TextField(help_text='Detailed activity description')),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('water_sports', 'Water Sports'), ('wellness', 'Wellness & Spa'), ('dining', 'Dining'), ('entertainment', 'Entertainment'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('nature', 'Nature')], default='adventure', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('expert', 'Expert')], default='easy', max_length=15)),
                ('duration', models.CharField(help_text="e.g., '2-3 hours', 'Full day', 'Half day'", max_length=50)),
                ('max_participants', models.IntegerField(default=10, help_text='Maximum number of participants')),
                ('min_age', models.IntegerField(default=0, help_text='Minimum age requirement (0 for no restriction)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=8)),
                ('icon_class', models.CharField(default='fas fa-star', help_text='Font Awesome icon class (e.g., fas fa-swimming-pool)', max_length=50)),
                ('image_placeholder', models.CharField(default='https://images.unsplash.com/photo-1544197150-b99a580bb7a8?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', help_text='Activity image URL', max_length=300)),
                ('background_color', models.CharField(default='#134a39', help_text='Hex color for card background', max_length=7)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured activities section')),
                ('requires_booking', models.BooleanField(default=True)),
                ('includes_equipment', models.BooleanField(default=False)),
                ('includes_guide', models.BooleanField(default=False)),
                ('includes_transport', models.BooleanField(default=False)),
                ('available_days', models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday', help_text='Comma-separated days of the week', max_length=100)),
                ('available_times', models.CharField(default='9:00 AM,2:00 PM', help_text='Comma-separated available start times', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Activity location', max_length=100)),
                ('what_to_bring', models.TextField(blank=True, help_text='What participants should bring')),
                ('included_items', models.TextField(blank=True, help_text="What's included in the activity")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-is_featured', '-is_available', 'category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_placeholder',
            field=models.CharField(default='https://via.placeholder.com/600x400/1e6b54/ffffff?text=Gallery+Image', max_length=200),
        ),
        migrations.AlterField(
            model_name='resort',
            name='hero_image_placeholder',
            field=models.CharField(default='https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1920&q=80', max_length=200),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image_placeholder',
            field=models.CharField(default='https://via.placeholder.com/400x300/134a39/ffffff?text=Room+Image', max_length=200),
        ),
    ]
