# Generated by Django 5.2.6 on 2025-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_gallery_media_type_gallery_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('rooms', models.IntegerField()),
                ('room_type', models.CharField(blank=True, choices=[('', 'No Preference'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('oceanview', 'Ocean View'), ('presidential', 'Presidential Suite')], max_length=20)),
                ('bed_preference', models.CharField(blank=True, choices=[('', 'No Preference'), ('king', 'King Bed'), ('queen', 'Queen Bed'), ('twin', 'Twin Beds')], max_length=10)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('occasion', models.CharField(blank=True, choices=[('', 'Select Occasion'), ('honeymoon', 'Honeymoon'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday'), ('business', 'Business Travel'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
