# Generated by Django 5.2.6 on 2025-09-30 17:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_activity_alter_gallery_image_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='detailed_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text content for activity detail page'),
        ),
    ]
