# Generated by Django 5.2.6 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_placeholder',
            field=models.CharField(default='https://via.placeholder.com/600x400/1e6b54/ffffff?text=Gallery+Image', max_length=200),
        ),
        migrations.AlterField(
            model_name='resort',
            name='hero_image_placeholder',
            field=models.CharField(default='https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1920&q=80', max_length=200),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image_placeholder',
            field=models.CharField(default='https://via.placeholder.com/400x300/134a39/ffffff?text=Room+Image', max_length=200),
        ),
    ]
