# Generated by Django 5.2.6 on 2025-09-30 17:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_activity_detailed_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='image_placeholder',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text content for room detail page'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_garden_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_kitchenette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_ocean_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured rooms section'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='main_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', help_text='Main room image URL', max_length=300),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_count',
            field=models.IntegerField(default=1, help_text='Number of available rooms of this type'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night (for admin reference only)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(help_text='Brief description for room cards'),
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the media item', max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image_url', models.CharField(blank=True, help_text='Image URL', max_length=300)),
                ('video_url', models.CharField(blank=True, help_text='Video URL (YouTube, Vimeo, or direct)', max_length=300)),
                ('video_thumbnail', models.CharField(blank=True, help_text='Video thumbnail image URL', max_length=300)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this image in room cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='resort.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
