# Generated by Django 5.2.6 on 2025-09-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_alter_gallery_image_placeholder_and_more'),
        ('resort', '0005_remove_roomtype_image_placeholder_and_more'),
    ]

    operations = [
    ]
