# Generated by Django 5.2.6 on 2025-10-26 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_remove_roomtype_image_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Blog post content with rich text formatting')),
                ('excerpt', models.TextField(blank=True, help_text='Short description for blog list (auto-generated if empty)', max_length=300)),
                ('author', models.CharField(default='Banbas Resort', help_text='Author name', max_length=100)),
                ('category', models.CharField(choices=[('resort', 'Resort News'), ('travel', 'Travel Tips'), ('local', 'Local Attractions'), ('food', 'Food & Dining'), ('events', 'Events'), ('general', 'General')], default='general', max_length=20)),
                ('featured_image', models.CharField(default='https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', help_text='Featured image URL for the blog post', max_length=300)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this blog post')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('published_date', models.DateTimeField(blank=True, help_text='Date to publish (leave blank for now)', null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
