# Generated by Django 5.2.6 on 2025-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_merge_20250930_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='preferred_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
