# Generated by Django 5.2.6 on 2025-11-02 15:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='OUR STORY', max_length=200)),
                ('subtitle', models.CharField(default='Story Behind Banbas | Sustainability | Chitwan National Park', max_length=300)),
                ('founders_narrative_title', models.CharField(default="Bashu Dhungana's Life Work", max_length=200)),
                ('founders_narrative_content', ckeditor.fields.RichTextField(blank=True)),
                ('management_partnership_title', models.CharField(default='Management Partnership', max_length=200)),
                ('management_partnership_content', ckeditor.fields.RichTextField(blank=True)),
                ('vision_and_design_title', models.CharField(default='Vision and Design', max_length=200)),
                ('vision_and_design_content', ckeditor.fields.RichTextField(blank=True)),
                ('main_image', models.CharField(default='https://images.unsplash.com/photo-1516426122078-c23e76319801?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', max_length=300)),
                ('secondary_image', models.CharField(default='https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
