# Generated by Django 5.2.6 on 2025-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='founders_narrative_image',
            field=models.CharField(default='https://www.banbasresort.com/static/img/b.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='management_partnership_image',
            field=models.CharField(default='https://www.banbasresort.com/static/img/c.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_and_design_image',
            field=models.CharField(default='https://www.banbasresort.com/static/img/a.jpg', max_length=300),
        ),
    ]
