# Generated by Django 5.2.6 on 2025-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0008_aboutpage_founders_narrative_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='show_price_publicly',
            field=models.BooleanField(default=False, help_text='Toggle to display the price badge on the public rooms page'),
        ),
    ]
