# Generated by Django 5.2.6 on 2025-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0008_aboutpage_founders_narrative_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_view_website', models.BooleanField(default=True)),
                ('show_rooms_page', models.BooleanField(default=True)),
                ('show_contact_page', models.BooleanField(default=True)),
                ('show_admin_docs', models.BooleanField(default=True)),
                ('nav_style', models.CharField(default='pills', help_text='Nav style hint for templates', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Navigation Settings',
            },
        ),
    ]
