# Generated by Django 5.2.6 on 2025-11-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0009_navigationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='show_admin_docs',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='show_contact_page',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='show_rooms_page',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='show_view_website',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_accommodation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_amenities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_book_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='show_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='nav_style',
            field=models.CharField(default='pills', max_length=20),
        ),
    ]
