# Generated by Django 5.2.6 on 2025-11-09 16:36

from django.db import migrations, models


def seed_gallery_categories(apps, schema_editor):
    Gallery = apps.get_model('resort', 'Gallery')
    GalleryCategory = apps.get_model('resort', 'GalleryCategory')

    default_categories = [
        ('rooms', 'Rooms'),
        ('amenities', 'Amenities'),
        ('dining', 'Dining'),
        ('exterior', 'Exterior'),
        ('activities', 'Activities'),
    ]

    slug_to_category = {}
    for display_order, (slug, name) in enumerate(default_categories):
        category_obj, _ = GalleryCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'display_order': display_order}
        )
        slug_to_category[slug] = category_obj

    for gallery_item in Gallery.objects.all():
        slug = getattr(gallery_item, 'category', None)
        if slug:
            category_obj = slug_to_category.get(slug)
            if not category_obj:
                category_obj, _ = GalleryCategory.objects.get_or_create(
                    slug=slug,
                    defaults={
                        'name': slug.replace('_', ' ').title(),
                        'display_order': GalleryCategory.objects.count()
                    }
                )
                slug_to_category[slug] = category_obj
            gallery_item.categories.add(category_obj)


def create_default_navigation_settings(apps, schema_editor):
    NavigationSettings = apps.get_model('resort', 'NavigationSettings')
    if not NavigationSettings.objects.exists():
        NavigationSettings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0009_roomtype_show_price_publicly'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home', models.BooleanField(default=True)),
                ('show_about', models.BooleanField(default=True)),
                ('show_rooms', models.BooleanField(default=True)),
                ('show_amenities', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_blog', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_activities', models.BooleanField(default=True)),
                ('book_button_label', models.CharField(default='Book A Stay', max_length=50)),
                ('book_button_url', models.CharField(default='/contact/', max_length=200)),
                ('show_book_button', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Settings',
                'verbose_name_plural': 'Navigation Settings',
            },
        ),
        migrations.RunPython(
            create_default_navigation_settings,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='gallery',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories for filtering on the gallery page.', related_name='gallery_items', to='resort.gallerycategory'),
        ),
        migrations.RunPython(
            seed_gallery_categories,
            reverse_code=migrations.RunPython.noop
        ),
    ]
